name: Lint

defaults:
  run:
    shell: pwsh

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  psscriptanalzyer:
    permissions:
      contents: read
      security-events: write
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install AnyPackage and ConvertToSARIF
        run: Install-Module AnyPackage, ConvertToSARIF -Force -AllowClobber

      - name: Run PSScriptAnalyzer
        run: |
          Import-Module AnyPackage, ConvertToSARIF
          Invoke-ScriptAnalyzer -Path . -Recurse | ConvertTo-SARIF -FilePath results.sarif

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
  
  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Lint markdown"
        uses: DavidAnson/markdownlint-cli2-action@v16
